import {
  StudentProfile,
  Goal,
  Exam,
  DSAProblem,
  Course,
  Task,
  RevisionItem,
  CalendarEvent,
  ResourceItem,
  JobApplication,
  NotificationItem,
  AptitudeTopic,
  CSFundamentalTopic,
  InterviewQuestion,
} from './types';

export const initialProfile: StudentProfile = {
  id: 'student-01',
  name: 'Alex Chen',
  email: 'alex.chen@university.edu',
  degree: 'B.Tech / B.E.',
  branch: 'Computer Science & Engineering (AI/ML)',
  college: 'National Institute of Technology',
  currentYearSemester: '3rd Year (6th Semester)',
  cgpa: 8.82,
  graduationYear: 2027,
  careerGoal: 'Software Development Engineer (SDE-1) & Applied ML',
  targetCompanies: ['Google', 'Microsoft', 'Atlassian', 'Amazon', 'Uber'],
  targetExams: ['GATE DA 2027', 'Semester Finals', 'AWS Solutions Architect'],
  dailyStudyHours: 3.5,
  preferredStudyTime: 'Evening',
  strongSubjects: ['Data Structures', 'Algorithms', 'Operating Systems', 'Python'],
  weakSubjects: ['Probability & Statistics', 'Linear Algebra', 'Computer Networks'],
  collegeStartTime: '09:00',
  collegeEndTime: '16:00',
  travelHoursDaily: 1.0,
  sleepHours: 7.5,
};

export const initialGoals: Goal[] = [
  {
    id: 'goal-1',
    name: 'Crack Tier-1 SDE Placement',
    category: 'Placement',
    targetDate: '2026-11-30',
    priority: 'High',
    progress: 68,
    requiredTopics: [
      'DSA 250+ Problems',
      'DBMS & SQL Queries',
      'Operating Systems Virtual Memory',
      'Computer Networks TCP/IP',
      'System Design Basics',
      '2 Full-Stack Projects',
      'Behavioral STAR Stories',
    ],
    completedTopics: [
      'DSA 250+ Problems',
      'DBMS & SQL Queries',
      'Operating Systems Virtual Memory',
      '2 Full-Stack Projects',
    ],
    dailyWeeklyTarget: '2 DSA problems/day + 1 Core CS subject review',
    description: 'Targeting Google, Microsoft, and Atlassian campus on-campus and off-campus recruitment drives.',
  },
  {
    id: 'goal-2',
    name: 'Score AIR < 300 in GATE DA / CS',
    category: 'Exam',
    targetDate: '2027-02-14',
    priority: 'High',
    progress: 46,
    requiredTopics: [
      'Probability & Random Variables',
      'Linear Algebra & Eigenvalues',
      'Calculus & Optimization',
      'Machine Learning Models',
      'AI & Search Heuristics',
      'Previous 10 Years Question Papers',
      '15 Full Mock Tests',
    ],
    completedTopics: [
      'Calculus & Optimization',
      'Linear Algebra & Eigenvalues',
      'Machine Learning Models',
    ],
    dailyWeeklyTarget: '1.5 hrs high-yield subject study + weekly mock revision',
    description: 'Aiming for top IISc/IIT M.Tech admissions or PSU research fellowships.',
  },
  {
    id: 'goal-3',
    name: 'Complete Full-Stack Cloud Project for Resume',
    category: 'Project',
    targetDate: '2026-10-25',
    priority: 'Medium',
    progress: 75,
    requiredTopics: [
      'System Architecture Diagram',
      'FastAPI Backend with Docker',
      'React Frontend with Tailwind',
      'CI/CD GitHub Actions',
      'AWS ECS Deployment',
    ],
    completedTopics: [
      'System Architecture Diagram',
      'FastAPI Backend with Docker',
      'React Frontend with Tailwind',
    ],
    dailyWeeklyTarget: '3 hrs over weekends',
    description: 'Distributed real-time collaborative document editor with WebSocket synchronization.',
  },
  {
    id: 'goal-4',
    name: 'Aptitude & Speed Math Mastery',
    category: 'Skill',
    targetDate: '2026-10-15',
    priority: 'Medium',
    progress: 60,
    requiredTopics: ['Time & Work', 'Percentages & Profit/Loss', 'Syllogisms', 'Data Interpretation Charts', 'Reading Comprehension'],
    completedTopics: ['Time & Work', 'Percentages & Profit/Loss', 'Syllogisms'],
    dailyWeeklyTarget: '30 mins every alternate day',
    description: 'Crucial for passing online assessment (OA) preliminary rounds.',
  },
];

export const initialExams: Exam[] = [
  {
    id: 'exam-1',
    name: 'GATE Data Science & AI (DA)',
    examDate: '2027-02-14',
    targetScore: 'AIR < 300 (Score 78+/100)',
    totalTopics: 28,
    completedTopics: 13,
    subjects: [
      {
        subjectName: 'Probability & Statistics',
        progress: 25,
        topics: [
          { id: 'p1', name: 'Bayes Theorem & Conditional Probability', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 8, completed: true },
          { id: 'p2', name: 'Random Variables & Expectation', difficulty: 'Hard', knowledgeLevel: 'Beginner', weightagePercent: 10, completed: false },
          { id: 'p3', name: 'Distributions (Binomial, Poisson, Normal)', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 9, completed: false },
          { id: 'p4', name: 'Hypothesis Testing & p-values', difficulty: 'Hard', knowledgeLevel: 'Beginner', weightagePercent: 8, completed: false },
        ],
      },
      {
        subjectName: 'Linear Algebra',
        progress: 45,
        topics: [
          { id: 'l1', name: 'Vector Spaces & Subspaces', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 7, completed: true },
          { id: 'l2', name: 'Eigenvalues & Diagonalization', difficulty: 'Hard', knowledgeLevel: 'Beginner', weightagePercent: 12, completed: false },
          { id: 'l3', name: 'Singular Value Decomposition (SVD)', difficulty: 'Hard', knowledgeLevel: 'Beginner', weightagePercent: 10, completed: false },
          { id: 'l4', name: 'Matrix Inverses & Determinants', difficulty: 'Easy', knowledgeLevel: 'Proficient', weightagePercent: 6, completed: true },
        ],
      },
      {
        subjectName: 'Calculus & Optimization',
        progress: 70,
        topics: [
          { id: 'c1', name: 'Maxima, Minima & Saddle Points', difficulty: 'Medium', knowledgeLevel: 'Proficient', weightagePercent: 8, completed: true },
          { id: 'c2', name: 'Gradient Descent & Convex Functions', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 9, completed: true },
        ],
      },
      {
        subjectName: 'Machine Learning',
        progress: 60,
        topics: [
          { id: 'm1', name: 'Supervised Learning (Regression & Trees)', difficulty: 'Medium', knowledgeLevel: 'Proficient', weightagePercent: 12, completed: true },
          { id: 'm2', name: 'SVMs & Kernel Tricks', difficulty: 'Hard', knowledgeLevel: 'Intermediate', weightagePercent: 10, completed: false },
          { id: 'm3', name: 'Clustering & PCA Dimensionality Reduction', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 9, completed: true },
        ],
      },
      {
        subjectName: 'Artificial Intelligence',
        progress: 30,
        topics: [
          { id: 'a1', name: 'A* and Informed Search Strategies', difficulty: 'Medium', knowledgeLevel: 'Intermediate', weightagePercent: 8, completed: true },
          { id: 'a2', name: 'Alpha-Beta Pruning & Adversarial Search', difficulty: 'Hard', knowledgeLevel: 'Beginner', weightagePercent: 7, completed: false },
        ],
      },
    ],
  },
  {
    id: 'exam-2',
    name: 'Semester 6 Midterms',
    examDate: '2026-10-28',
    targetScore: 'CGPA >= 9.0 (Marks > 85%)',
    totalTopics: 16,
    completedTopics: 11,
    subjects: [
      {
        subjectName: 'Compiler Design',
        progress: 65,
        topics: [
          { id: 'cd1', name: 'Lexical Analysis & DFA Minimization', difficulty: 'Medium', knowledgeLevel: 'Proficient', weightagePercent: 20, completed: true },
          { id: 'cd2', name: 'LL(1) & LR(1) Parsers', difficulty: 'Hard', knowledgeLevel: 'Intermediate', weightagePercent: 25, completed: false },
          { id: 'cd3', name: 'Intermediate Code Generation', difficulty: 'Medium', knowledgeLevel: 'Beginner', weightagePercent: 20, completed: false },
        ],
      },
      {
        subjectName: 'Cloud Computing & Distributed Systems',
        progress: 80,
        topics: [
          { id: 'cc1', name: 'CAP Theorem & Consistency Models', difficulty: 'Medium', knowledgeLevel: 'Proficient', weightagePercent: 25, completed: true },
          { id: 'cc2', name: 'Kubernetes Pod Lifecycle & Raft Consensus', difficulty: 'Hard', knowledgeLevel: 'Intermediate', weightagePercent: 30, completed: true },
        ],
      },
    ],
  },
];

export const initialCourses: Course[] = [
  {
    id: 'course-1',
    name: 'Deep Learning Specialization',
    platform: 'Coursera',
    instructor: 'Andrew Ng (DeepLearning.AI)',
    courseUrl: 'https://www.coursera.org/specializations/deep-learning',
    totalLectures: 64,
    completedLectures: 38,
    estimatedTotalHours: 32,
    completedHours: 19,
    startDate: '2026-08-10',
    targetCompletionDate: '2026-10-31',
    priority: 'High',
    notes: 'Currently on Course 3: Structuring Machine Learning Projects.',
  },
  {
    id: 'course-2',
    name: 'Striver A2Z DSA Course & Sheet',
    platform: 'YouTube',
    instructor: 'Raj Vikramaditya (takeUforward)',
    courseUrl: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    totalLectures: 140,
    completedLectures: 92,
    estimatedTotalHours: 70,
    completedHours: 46,
    startDate: '2026-07-01',
    targetCompletionDate: '2026-11-15',
    priority: 'High',
    notes: 'Dynamic Programming section active. Grinding 1D & 2D DP.',
  },
  {
    id: 'course-3',
    name: 'MIT 18.06 Linear Algebra',
    platform: 'NPTEL',
    instructor: 'Prof. Gilbert Strang',
    courseUrl: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    totalLectures: 35,
    completedLectures: 16,
    estimatedTotalHours: 28,
    completedHours: 13,
    startDate: '2026-08-20',
    targetCompletionDate: '2026-11-30',
    priority: 'Medium',
    notes: 'Focusing on Lecture 21 & 22: Eigenvalues and Diagonalization.',
  },
  {
    id: 'course-4',
    name: 'CS50W: Web Programming with Python and JavaScript',
    platform: 'edX',
    instructor: 'Brian Yu (Harvard University)',
    courseUrl: 'https://cs50.harvard.edu/web/',
    totalLectures: 24,
    completedLectures: 22,
    estimatedTotalHours: 20,
    completedHours: 18.5,
    startDate: '2026-06-15',
    targetCompletionDate: '2026-10-10',
    priority: 'Low',
    notes: 'Only final capstone project submission remaining.',
  },
];

export const initialDSAProblems: DSAProblem[] = [
  {
    id: 'dsa-1',
    title: 'Two Sum',
    topic: 'Arrays',
    difficulty: 'Easy',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/two-sum/',
    status: 'Solved',
    accuracyRate: 98,
    solvedAt: '2026-09-12',
    notes: 'Hash map single-pass lookup. O(N) time and O(N) space.',
  },
  {
    id: 'dsa-2',
    title: '3Sum',
    topic: 'Arrays',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/3sum/',
    status: 'Solved',
    accuracyRate: 85,
    solvedAt: '2026-09-14',
    notes: 'Sort array then use two pointers. Skip duplicates to prevent duplicate triplets.',
  },
  {
    id: 'dsa-3',
    title: 'Longest Substring Without Repeating Characters',
    topic: 'Strings',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/longest-substring-without-repeating-characters/',
    status: 'Solved',
    accuracyRate: 92,
    solvedAt: '2026-09-15',
    notes: 'Sliding window with character index hash table.',
  },
  {
    id: 'dsa-4',
    title: 'Koko Eating Bananas',
    topic: 'Binary Search',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/koko-eating-bananas/',
    status: 'Solved',
    accuracyRate: 90,
    solvedAt: '2026-09-20',
    notes: 'Binary search on the answer range [1, max(piles)].',
  },
  {
    id: 'dsa-5',
    title: 'Search in Rotated Sorted Array',
    topic: 'Binary Search',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/',
    status: 'Solved',
    accuracyRate: 88,
    solvedAt: '2026-09-22',
    notes: 'One half is always sorted; verify which half target falls into.',
  },
  {
    id: 'dsa-6',
    title: 'LRU Cache',
    topic: 'Linked Lists',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/lru-cache/',
    status: 'Solved',
    accuracyRate: 94,
    solvedAt: '2026-09-24',
    notes: 'Doubly Linked List + HashMap for O(1) get and put.',
  },
  {
    id: 'dsa-7',
    title: 'Lowest Common Ancestor of a Binary Tree',
    topic: 'Trees',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/',
    status: 'Solved',
    accuracyRate: 86,
    solvedAt: '2026-09-25',
    notes: 'Post-order traversal checking left and right subtrees.',
  },
  {
    id: 'dsa-8',
    title: 'Course Schedule (Cycle in Directed Graph)',
    topic: 'Graphs',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/course-schedule/',
    status: 'Solved',
    accuracyRate: 82,
    solvedAt: '2026-09-26',
    notes: 'Kahn algorithm using in-degree array or DFS with 3-state coloring.',
  },
  {
    id: 'dsa-9',
    title: 'Coin Change',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/coin-change/',
    status: 'Solved',
    accuracyRate: 80,
    solvedAt: '2026-09-27',
    notes: 'Bottom-up DP dp[i] = min(dp[i], dp[i - coin] + 1). Base dp[0] = 0.',
  },
  {
    id: 'dsa-10',
    title: 'Longest Increasing Subsequence',
    topic: 'Dynamic Programming',
    difficulty: 'Medium',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/longest-increasing-subsequence/',
    status: 'In Progress',
    accuracyRate: 75,
    notes: 'O(N^2) DP mastered; practicing O(N log N) patience sorting with binary search.',
  },
  {
    id: 'dsa-11',
    title: 'Trapping Rain Water',
    topic: 'Stack',
    difficulty: 'Hard',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/trapping-rain-water/',
    status: 'To Do',
    notes: 'Two pointers approach vs monotonic stack comparison.',
  },
  {
    id: 'dsa-12',
    title: 'Median of Two Sorted Arrays',
    topic: 'Binary Search',
    difficulty: 'Hard',
    platform: 'LeetCode',
    url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/',
    status: 'To Do',
    notes: 'Binary search partition technique on shorter array.',
  },
];

export const initialTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Linear Algebra: Eigenvalues & Diagonalization Lecture',
    description: 'Watch MIT 18.06 Lecture 21 & derive characteristic polynomial equations',
    priority: 'High',
    deadline: '2026-09-28',
    timeSlot: '17:00 - 18:00',
    estimatedDurationMins: 45,
    category: 'Exam',
    isRecurring: false,
    completed: false,
  },
  {
    id: 'task-2',
    title: 'Solve 2 LeetCode Mediums on Binary Search',
    description: 'Solve #875 Koko Eating Bananas & #74 Search 2D Matrix',
    priority: 'High',
    deadline: '2026-09-28',
    timeSlot: '06:30 - 07:30',
    estimatedDurationMins: 50,
    category: 'DSA',
    isRecurring: true,
    completed: true,
    completedAt: '2026-09-28T07:25:00Z',
  },
  {
    id: 'task-3',
    title: 'Spaced Repetition: SQL Indexing & Normalization Flashcards',
    description: 'Review B-Tree vs Hash index and 3NF vs BCNF differences',
    priority: 'Medium',
    deadline: '2026-09-28',
    timeSlot: '20:30 - 21:00',
    estimatedDurationMins: 30,
    category: 'Revision',
    isRecurring: false,
    completed: false,
  },
  {
    id: 'task-4',
    title: 'Deep Learning Week 3: Hyperparameter Tuning Video',
    description: 'Complete Coursera video quiz on Batch Normalization',
    priority: 'Medium',
    deadline: '2026-09-28',
    timeSlot: '21:15 - 22:00',
    estimatedDurationMins: 40,
    category: 'Course',
    isRecurring: false,
    completed: false,
  },
  {
    id: 'task-5',
    title: 'Missed Yesterday: Operating Systems Virtual Memory Paging',
    description: 'Incomplete from yesterday due to college lab submission. Needs rescheduling!',
    priority: 'High',
    deadline: '2026-09-27',
    estimatedDurationMins: 35,
    category: 'Placement',
    isRecurring: false,
    completed: false,
    isMissed: true,
  },
  {
    id: 'task-6',
    title: 'Apply to Uber & Microsoft University Internships',
    description: 'Check careers portal, customize resume bullet points with metrics',
    priority: 'Medium',
    deadline: '2026-09-29',
    estimatedDurationMins: 45,
    category: 'Placement',
    isRecurring: false,
    completed: false,
  },
  {
    id: 'task-7',
    title: 'Weekly 60-min DSA Mock Contest on LeetCode',
    description: 'Simulate real OA environment with camera & strict timer',
    priority: 'High',
    deadline: '2026-10-03',
    estimatedDurationMins: 60,
    category: 'DSA',
    isRecurring: true,
    completed: false,
  },
];

export const initialRevisions: RevisionItem[] = [
  {
    id: 'rev-1',
    topicName: 'Binary Search on Rotated Sorted Array',
    subject: 'DSA',
    sourceType: 'DSA',
    learnedDate: '2026-09-27',
    stage: 1, // Day 1
    nextRevisionDate: '2026-09-28',
    status: 'Due Today',
  },
  {
    id: 'rev-2',
    topicName: 'Database Indexing: B+ Trees vs Hash',
    subject: 'DBMS',
    sourceType: 'CS Fundamentals',
    learnedDate: '2026-09-21',
    stage: 2, // Day 7
    nextRevisionDate: '2026-09-28',
    status: 'Due Today',
  },
  {
    id: 'rev-3',
    topicName: 'TCP 3-Way Handshake & Congestion Control',
    subject: 'Computer Networks',
    sourceType: 'CS Fundamentals',
    learnedDate: '2026-09-07',
    stage: 3, // Day 21
    nextRevisionDate: '2026-09-29',
    status: 'Upcoming',
  },
  {
    id: 'rev-4',
    topicName: 'Bayes Theorem & Conditional Probability',
    subject: 'Probability',
    sourceType: 'Exam',
    learnedDate: '2026-08-14',
    stage: 4, // Day 45
    nextRevisionDate: '2026-10-02',
    status: 'Upcoming',
  },
];

export const initialCalendarEvents: CalendarEvent[] = [
  {
    id: 'cal-1',
    title: 'Morning DSA Practice (Binary Search)',
    date: '2026-09-28',
    startTime: '06:30',
    endTime: '07:30',
    category: 'DSA',
    completed: true,
  },
  {
    id: 'cal-2',
    title: 'College Lectures & Operating Systems Lab',
    date: '2026-09-28',
    startTime: '09:00',
    endTime: '16:00',
    category: 'College',
    completed: true,
  },
  {
    id: 'cal-3',
    title: 'GATE DA: Linear Algebra Lecture 21',
    date: '2026-09-28',
    startTime: '17:00',
    endTime: '18:00',
    category: 'Exam',
    completed: false,
  },
  {
    id: 'cal-4',
    title: 'Spaced Repetition: SQL Indexing & Normalization',
    date: '2026-09-28',
    startTime: '20:30',
    endTime: '21:00',
    category: 'Revision',
    completed: false,
  },
  {
    id: 'cal-5',
    title: 'Deep Learning Batch Norm Lecture',
    date: '2026-09-28',
    startTime: '21:15',
    endTime: '22:00',
    category: 'Course',
    completed: false,
  },
  {
    id: 'cal-6',
    title: 'Atlassian Online Assessment (OA)',
    date: '2026-10-04',
    startTime: '10:00',
    endTime: '11:45',
    category: 'Placement',
    description: '3 coding questions on HackerRank (90 mins).',
  },
  {
    id: 'cal-7',
    title: 'Semester Midterm: Compiler Design',
    date: '2026-10-28',
    startTime: '09:30',
    endTime: '12:30',
    category: 'Exam',
  },
];

export const initialApplications: JobApplication[] = [
  {
    id: 'app-1',
    company: 'Google',
    role: 'Software Engineering Intern (Summer 2027)',
    applicationDate: '2026-09-10',
    deadline: '2026-10-15',
    status: 'Applied',
    jobLink: 'https://careers.google.com/jobs/results/',
    notes: 'Referred by senior alumni on LinkedIn. Application under review.',
    salaryPackage: '₹1.15L / month internship stipend',
  },
  {
    id: 'app-2',
    company: 'Atlassian',
    role: 'Associate Software Engineer',
    applicationDate: '2026-09-12',
    deadline: '2026-09-30',
    status: 'OA Scheduled',
    testDate: '2026-10-04',
    jobLink: 'https://www.atlassian.com/company/careers',
    notes: 'Received HackerRank test link. Focus on Graph and DP problems.',
    salaryPackage: '₹22 LPA CTC',
  },
  {
    id: 'app-3',
    company: 'Microsoft',
    role: 'Software Engineer (Campus Drive)',
    applicationDate: '2026-09-15',
    deadline: '2026-10-01',
    status: 'OA Completed',
    interviewDate: '2026-10-12',
    jobLink: 'https://careers.microsoft.com',
    notes: 'Codility assessment cleared 3/3 test cases. Technical round scheduled.',
    salaryPackage: '₹24.5 LPA CTC',
  },
  {
    id: 'app-4',
    company: 'Amazon',
    role: 'SDE Intern',
    applicationDate: '2026-09-02',
    status: 'Interview',
    interviewDate: '2026-10-08',
    jobLink: 'https://amazon.jobs',
    notes: 'Round 1 technical phone screen coming up. Brush up Leadership Principles & STAR stories.',
    salaryPackage: '₹80K / month internship stipend',
  },
  {
    id: 'app-5',
    company: 'Uber',
    role: 'Backend Engineering Intern',
    applicationDate: '2026-09-24',
    deadline: '2026-10-10',
    status: 'Wishlist',
    jobLink: 'https://www.uber.com/us/en/careers/',
    notes: 'Waiting for alumni referral before hitting submit button.',
    salaryPackage: '₹1.2L / month internship stipend',
  },
  {
    id: 'app-6',
    company: 'Salesforce',
    role: 'Software Engineering Trainee',
    applicationDate: '2026-08-20',
    status: 'Selected',
    jobLink: 'https://salesforce.com/careers',
    notes: 'Received pre-placement offer! Joining as back-up tier-1 option.',
    salaryPackage: '₹19 LPA CTC',
  },
];

export const initialAptitudeTopics: AptitudeTopic[] = [
  { id: 'apt-1', category: 'Quantitative', name: 'Time, Speed & Distance', problemsPracticed: 45, accuracy: 88, masteryLevel: 'Mastered' },
  { id: 'apt-2', category: 'Quantitative', name: 'Probability & Permutations', problemsPracticed: 35, accuracy: 68, masteryLevel: 'Needs Practice' },
  { id: 'apt-3', category: 'Logical', name: 'Seating Arrangements & Puzzles', problemsPracticed: 50, accuracy: 92, masteryLevel: 'Mastered' },
  { id: 'apt-4', category: 'Logical', name: 'Syllogisms & Logical Deductions', problemsPracticed: 30, accuracy: 84, masteryLevel: 'Good' },
  { id: 'apt-5', category: 'Data Interpretation', name: 'Bar Charts & Pie Charts', problemsPracticed: 25, accuracy: 90, masteryLevel: 'Mastered' },
  { id: 'apt-6', category: 'Verbal', name: 'Reading Comprehension & Critical Reasoning', problemsPracticed: 20, accuracy: 82, masteryLevel: 'Good' },
];

export const initialCSFundamentals: CSFundamentalTopic[] = [
  { id: 'cs-1', subject: 'DBMS', topic: 'Indexing (B+ Tree vs Hash vs Bitmap)', status: 'Revised', notes: 'B+ trees support range queries O(log N). Hash is O(1) for equality only.' },
  { id: 'cs-2', subject: 'DBMS', topic: 'ACID Properties & Isolation Levels', status: 'Interview Ready', notes: 'Dirty Read, Non-Repeatable Read, Phantom Read.' },
  { id: 'cs-3', subject: 'SQL', topic: 'Window Functions (ROW_NUMBER, RANK, DENSE_RANK)', status: 'Interview Ready', notes: 'DENSE_RANK doesn\'t skip rank numbers.' },
  { id: 'cs-4', subject: 'Operating Systems', topic: 'Virtual Memory & Page Replacement (LRU, FIFO)', status: 'In Progress', notes: 'Review Belady\'s Anomaly in FIFO.' },
  { id: 'cs-5', subject: 'Operating Systems', topic: 'Process Synchronization & Mutex vs Semaphore', status: 'Interview Ready', notes: 'Counting semaphore vs binary semaphore.' },
  { id: 'cs-6', subject: 'Computer Networks', topic: 'TCP 3-Way Handshake & Flow Control', status: 'In Progress', notes: 'SYN, SYN-ACK, ACK. Sliding window protocol.' },
  { id: 'cs-7', subject: 'Computer Networks', topic: 'DNS Resolution & HTTPS TLS Handshake', status: 'Not Started', notes: 'Certificate authority, symmetric session key.' },
  { id: 'cs-8', subject: 'OOP', topic: 'Polymorphism (Runtime vs Compile Time) & SOLID', status: 'Interview Ready', notes: 'Virtual tables, dynamic dispatch.' },
];

export const initialInterviewQuestions: InterviewQuestion[] = [
  { id: 'iq-1', category: 'Technical', question: 'How does hash table collision resolution work (Chaining vs Open Addressing)?', prepared: true },
  { id: 'iq-2', category: 'Technical', question: 'Explain the difference between a process and a thread, and what is shared between threads?', prepared: true },
  { id: 'iq-3', category: 'Behavioral', question: 'Tell me about a time you faced a difficult technical challenge and how you solved it (STAR method)?', prepared: true },
  { id: 'iq-4', category: 'Behavioral', question: 'How do you prioritize when you have multiple competing deadlines (College vs Placements)?', prepared: true },
  { id: 'iq-5', category: 'Resume', question: 'Explain the architecture and trade-offs of your distributed collaborative document editor project.', prepared: true },
  { id: 'iq-6', category: 'HR', question: 'Why do you want to join our company and where do you see yourself in 3 years?', prepared: false },
];

export const initialResources: ResourceItem[] = [
  {
    id: 'res-1',
    title: 'Striver A2Z DSA Sheet Roadmap PDF',
    type: 'PDF',
    subject: 'DSA',
    platform: 'takeUforward',
    difficulty: 'Intermediate',
    url: 'https://takeuforward.org/strivers-a2z-dsa-course/strivers-a2z-dsa-course-sheet-2/',
    completed: false,
    notes: 'Best structured curriculum for interview coding rounds.',
  },
  {
    id: 'res-2',
    title: 'MIT 18.06 Gilbert Strang Lecture Notes & Syllabus',
    type: 'Website',
    subject: 'Linear Algebra',
    platform: 'MIT OCW',
    difficulty: 'Advanced',
    url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    completed: true,
    notes: 'Intuitive geometric understanding of eigenvectors and projections.',
  },
  {
    id: 'res-3',
    title: 'NeetCode 150 Problem Explanations & Code',
    type: 'Coding Problem',
    subject: 'DSA',
    platform: 'NeetCode.io',
    difficulty: 'Intermediate',
    url: 'https://neetcode.io/practice',
    completed: false,
    notes: 'Excellent clean Python/Java implementations with video explanations.',
  },
  {
    id: 'res-4',
    title: 'Operating Systems: Three Easy Pieces (OSTEP)',
    type: 'Book',
    subject: 'Operating Systems',
    platform: 'Arpaci-Dusseau Books',
    difficulty: 'Intermediate',
    url: 'https://pages.cs.wisc.edu/~remzi/OSTEP/',
    completed: false,
    notes: 'Chapters on Virtualization and Concurrency are gold standard.',
  },
  {
    id: 'res-5',
    title: 'SQL Zoo Interactive Practice Exercises',
    type: 'Website',
    subject: 'SQL',
    platform: 'SQLZoo',
    difficulty: 'Beginner',
    url: 'https://sqlzoo.net/',
    completed: true,
    notes: 'Self-evaluating interactive queries on JOINs and aggregate filters.',
  },
];

export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Priority Task Due Soon',
    message: 'Linear Algebra – Eigenvalues lecture is scheduled for 5:00 PM today.',
    category: 'task',
    timestamp: '10 mins ago',
    read: false,
  },
  {
    id: 'notif-2',
    title: 'Spaced Repetition Review Ready',
    message: 'Day 7 revision for SQL Indexing & Normalization is due today.',
    category: 'revision',
    timestamp: '1 hour ago',
    read: false,
  },
  {
    id: 'notif-3',
    title: 'Upcoming Assessment in 6 Days',
    message: 'Atlassian Online Assessment (HackerRank) is scheduled for Oct 4, 10:00 AM.',
    category: 'placement',
    timestamp: 'Yesterday',
    read: true,
  },
  {
    id: 'notif-4',
    title: 'Consistency Streak Active! 🔥',
    message: '14 consecutive days of study logged. Keep the momentum going!',
    category: 'streak',
    timestamp: '2 days ago',
    read: true,
  },
];
